# Generated by Django 3.2.15 on 2022-09-23 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoplee', '0002_auto_20220923_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='shortBio',
            new_name='bio',
        ),
    ]
