# Generated by Django 3.2.15 on 2022-09-23 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplee', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('discounted_price', models.FloatField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
