# Generated by Django 3.2.15 on 2022-09-23 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoplee', '0007_auto_20220923_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product'},
        ),
    ]
