# Generated by Django 3.2.15 on 2022-09-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplee', '0012_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='static/images'),
        ),
    ]
