# Generated by Django 3.2.15 on 2022-09-23 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoplee', '0013_alter_productimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='reviews',
            new_name='review',
        ),
    ]
