# Generated by Django 3.2.15 on 2022-09-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplee', '0014_rename_reviews_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='detail',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='', null=True, upload_to='static/images'),
        ),
    ]
