# Generated by Django 3.2.15 on 2022-09-24 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplee', '0016_auto_20220925_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
